version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  chatbot:
    build: .
    container_name: chatbot
    hostname: chatbot
    env_file:
      - .env
    ports:
      - "7860:7860"
    depends_on:
      - postgres
