CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY NULL DEFAULT gen_random_uuid(),
  "name" TEXT NOT NULL,
  handle TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS locations (
  id UUID PRIMARY KEY NULL DEFAULT GEN_RANDOM_UUID(),
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS tweets (
  id UUID PRIMARY KEY NULL DEFAULT GEN_RANDOM_UUID(),
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  "text" TEXT NOT NULL,
  "owner" UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "location" UUID NOT NULL REFERENCES locations(id) ON DELETE CASCADE
);